### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by misticwonder** [mw-experts/rsql#1]
- [ ]  Build and publish package 
- [ ] Github actions
- [ ] Setup repo, protect branches, remove projects
- [ ] Cover filter with more tests
- [ ] Add support for wildcard * and documentation to it
- [ ] Show this lib to colleagues
